"""Native source-change runtime. Compilation itself never writes source files."""
from .ia import encoded
from .native import RAX, RCX, RDX, R8, R9, R10, RSP, RBP


def emit_runtime(e, compiler):
    used = {ins.args[0] for fn in compiler.functions for ins in fn.instructions if ins.op == "ia_apply"}
    if not used:
        return
    # Open with exclusive sharing, verify exact bytes while keeping the handle.
    e.start("rt_ia_open", 5, 7)
    e.store(RBP, -8, RDX)
    e.store(RBP, -16, R8)
    e.immediate(RDX, 0xC0000000)  # GENERIC_READ | GENERIC_WRITE
    e.immediate(R8, 0)
    e.immediate(R9, 0)
    for offset, value in ((32, 3), (40, 0x80), (48, 0)):
        e.immediate(RAX, value)
        e.store(RSP, offset, RAX)
    e.external("CreateFileW")
    e.store(RBP, -24, RAX)
    e.immediate(R10, -1)
    e.compare(RAX, R10)
    fail, close, free, ok = (e.fresh() for _ in range(4))
    e.jump(fail, 0x84)
    e.load(RCX, RBP, -16)
    e.immediate(R10, 1)
    e.binary(0x01, RCX, R10)
    e.call("rt_alloc")
    e.store(RBP, -32, RAX)
    e.move(RDX, RAX)
    e.load(RCX, RBP, -24)
    e.load(R8, RBP, -16)
    e.immediate(R10, 1)
    e.binary(0x01, R8, R10)
    e.memory(0x8D, R9, RBP, -40)
    e.immediate(RAX, 0)
    e.store(RBP, -40, RAX)
    e.store(RSP, 32, RAX)
    e.external("ReadFile")
    e.test(RAX)
    e.jump(free, 0x84)
    e.load(RAX, RBP, -40)
    e.load(R10, RBP, -16)
    e.compare(RAX, R10)
    e.jump(free, 0x85)
    e.load(RCX, RBP, -32)
    e.load(RDX, RBP, -8)
    e.load(R8, RBP, -16)
    e.external("memcmp")
    e.test(RAX)
    e.jump(free, 0x85)
    e.load(RCX, RBP, -32)
    e.external("free")
    e.load(RAX, RBP, -24)
    e.jump(ok)
    e.label(free)
    e.load(RCX, RBP, -32)
    e.external("free")
    e.label(close)
    e.load(RCX, RBP, -24)
    e.external("CloseHandle")
    e.label(fail)
    e.address(RCX, e.string("sys.ia.apply: arquivo alterado, bloqueado ou indisponivel"))
    e.call("rt_error_set")
    e.immediate(RAX, -1)
    e.label(ok)
    e.epilogue()
    e.end()

    # Write through the still-locked handle; callers retain rollback snapshots.
    e.start("rt_ia_write", 4, 5)
    for slot, reg in ((-8, RCX), (-16, RDX), (-24, R8)):
        e.store(RBP, slot, reg)
    e.immediate(RDX, 0)
    e.immediate(R8, 0)
    e.immediate(R9, 0)
    e.external("SetFilePointerEx")
    failed, done = e.fresh(), e.fresh()
    e.test(RAX)
    e.jump(failed, 0x84)
    e.load(RCX, RBP, -8)
    e.load(RDX, RBP, -16)
    e.load(R8, RBP, -24)
    e.memory(0x8D, R9, RBP, -32)
    e.immediate(RAX, 0)
    e.store(RBP, -32, RAX)
    e.store(RSP, 32, RAX)
    e.external("WriteFile")
    e.test(RAX)
    e.jump(failed, 0x84)
    e.load(RAX, RBP, -32)
    e.load(R10, RBP, -24)
    e.compare(RAX, R10)
    e.jump(failed, 0x85)
    e.load(RCX, RBP, -8)
    e.external("SetEndOfFile")
    e.test(RAX)
    e.jump(failed, 0x84)
    e.load(RCX, RBP, -8)
    e.external("FlushFileBuffers")
    e.test(RAX)
    e.jump(failed, 0x84)
    e.immediate(RAX, 1)
    e.jump(done)
    e.label(failed)
    e.immediate(RAX, 0)
    e.label(done)
    e.epilogue()
    e.end()

    for number in sorted(used):
        files = compiler.changes[number]["files"]
        e.start(f"ia_apply_{number}", len(files) + 1)
        cleanup, rollback, done = e.fresh(), e.fresh(), e.fresh()
        e.immediate(RAX, -1)
        for i in range(len(files)):
            e.store(RBP, -8 * (i + 1), RAX)
        for i, file in enumerate(files):
            before = encoded(file, "before")
            e.address(RCX, e.blob(file["path"].encode("utf-16-le") + b"\0\0"))
            e.address(RDX, e.blob(before))
            e.immediate(R8, len(before))
            e.call("rt_ia_open")
            e.store(RBP, -8 * (i + 1), RAX)
            e.immediate(R10, -1)
            e.compare(RAX, R10)
            e.jump(cleanup, 0x84)
        for i, file in enumerate(files):
            after = encoded(file, "after")
            e.load(RCX, RBP, -8 * (i + 1))
            e.address(RDX, e.blob(after))
            e.immediate(R8, len(after))
            e.call("rt_ia_write")
            e.test(RAX)
            e.jump(rollback, 0x84)
        e.jump(cleanup)
        e.label(rollback)
        error_slot = -8 * (len(files) + 1)
        e.address(RAX, e.string("sys.ia.apply: falha de escrita; originais restaurados"))
        e.store(RBP, error_slot, RAX)
        for i, file in enumerate(files):
            before = encoded(file, "before")
            e.load(RCX, RBP, -8 * (i + 1))
            e.address(RDX, e.blob(before))
            e.immediate(R8, len(before))
            e.call("rt_ia_write")
            e.test(RAX)
            restored = e.fresh()
            e.jump(restored, 0x85)
            e.address(RAX, e.string("sys.ia.apply: falha de escrita e de rollback; recupere o snapshot do preview"))
            e.store(RBP, error_slot, RAX)
            e.label(restored)
        e.load(RCX, RBP, error_slot)
        e.call("rt_error_set")
        e.label(cleanup)
        for i in range(len(files)):
            e.load(RCX, RBP, -8 * (i + 1))
            e.immediate(R10, -1)
            e.compare(RCX, R10)
            skip = e.fresh()
            e.jump(skip, 0x84)
            e.external("CloseHandle")
            e.label(skip)
        e.label(done)
        e.epilogue()
        e.end()
